####
#
#    File: /etc/rsyslog.d/20-ufw.conf
#    Author: Truc Minh Phan <immersedone>
#    Last Modified: Truc Minh Phan (20/01/2020)
#    Description: 
#
#    This file has been modified to change the log
#    location of UFW.
#
#
##


# Log kernel generated UFW log messages to file
:msg,contains,"[UFW " /var/log/ufw/ufw.log

# Uncomment the following to stop logging anything that matches the last rule.
# Doing this will stop logging kernel generated UFW log messages to the file
# normally containing kern.* messages (eg, /var/log/kern.log)
#& stop
