####
#
#    File: /etc/nginx/nginx.conf
#    Author: Truc Minh Phan <immersedone>
#    Last Modified: Truc Minh Phan (20/01/2020)
#    Description:
#
#    This file contains the base configuration for
#    Nginx to be used as a reverse-proxy. It is the
#    over-arching configuration that then calls upon
#    the individual site configurations.
#
#    Current modifications include:
#        - Include ModSecurity
#        - Disable Server Tokens
#        - Change Server Header to be 'Immersed'
#        - Modified Nginx Log Location
#
#
##


# Nginx worker process user
user {NGINX_USER};
worker_processes auto;
pid /run/nginx.pid;
worker_rlimit_nofile 102400;
include /etc/nginx/modules-enabled/*.conf;

events {
        ## Default Event Configurations
        # worker_connections 768;
        # multi_accept on;

        ## Prevent SlowLoris DOS Attacks
        worker_connections 100000;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        ## Server Header Configuration (will be dynamically configured)
        {SERVER_HEADER_CONFIG}

        ## Add ModSecurity (will be dynamically configured)
        {MODSECURITY_CONFIG}

        # server_names_hash_bucket_size 64;
        server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ## Drop TLSv1 from SSL Protocols as it is a weaker cipher
        ssl_protocols TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;


        ## ngx_http_limit_req_module: Mitigate DDOS Attacks alongside Fail2Ban
        limit_req_zone $binary_remote_addr zone=borderforce:10m rate=300r/s;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
