####
#    File: /etc/apache2/conf-available/opt-accept-encoding.conf
#    Author: Truc Minh Phan <immersedone>
#    Last Modified: Truc Minh Phan (18/12/2019)
#    Description:
#
#    This file contains the configurations to turn on Vary: Accept-Encoding
#    headers for certain filetypes.
#
#    Dependency: mod_expires.so
#
##

<IfModule mod_headers.c>
  <FilesMatch ".(js|css|xml|gz|html)$">
    Header append Vary: Accept-Encoding
  </FilesMatch>
</IfModule>
