####
#    File: /etc/apache2/conf-available/opt-cache-control.conf
#    Author: Truc Minh Phan <immersedone>
#    Last Modified: Truc Minh Phan (18/12/2019)
#    Description:
#
#    This file contains the configurations to turn on Cache-Control
#    headers for certain filetypes.
#
#    Dependency: mod_expires.so
#
##

<filesMatch ".(ico|pdf|flv|jpg|jpeg|png|gif|js|css|swf)$">
Header set Cache-Control "max-age=604800, public"
</filesMatch>
